### PR TITLE
4 get reviews

### PR DESCRIPTION
**Pull request by RossKeen**

### CODE REVIEW

**Review by hevdevs — CHANGES_REQUESTED** [review]
Looking good! have you tested for a 400 error yet? if not we are going to need one to handle for the case of a "bad path" i.e. /api/reviews/banana. This can be done in our app and work for all endpoints, but we want to be implementing it now and testing for it.

**Comment by RossKeen** [comment]
Thanks for the feedback! Yes, this was accounted for on the /api/categories endpoint and was implemented to account for all endpoints. 

In my testing suite this is within the describe block of "/api/categories" and then "GET". Would it be clearer if this error handling was in its own describe block since it accounts for all endpoints?

**Comment by hevdevs** [comment]
Sweet! that's all good then, I'd say up it's up to you, a catch all 400 describe test block is good but i'd also do a test endpoint to show that it still works with queries/params

**Comment by RossKeen** [comment]
This has now been implemented and I needed to account for a PSQL error when dealing with a bad path involving params - great shout! 

The test suite has also been reorganised to make it clearer that the 400 test applies to all endpoints.

**Pull request merged**
